enum ACTIONS {
  SET_SEARCHED_PHRASE = 'SET_SEARCHED_PHRASE',
  SET_DROPDOWN_ACTIVE = 'SET_DROPDOWN_ACTIVE',
  SET_DROPDOWN_UNACTIVE = 'SET_DROPDOWN_UNACTIVE',
  DISPLAY_SEARCH_RESULTS = 'DISPLAY_SEARCH_RESULTS'
}

export default ACTIONS;
